site_name: Educatio Nova
site_url: https://educatio-nova.github.io/

theme:
  name: material
  icon:
    logo: material/school
  palette:
    - scheme: default
      primary: blue
      accent: light blue
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Cambiar a modo oscuro
  font:
    text: Inter
    code: JetBrains Mono

nav:
  - Inicio: index.md
  - Publicaciones: publicaciones.md

plugins:
  - search
  - blogging:
      dirs: [blog]
  - rss:
      match_path: blog/.*
      feed_title: "Educatio Nova - Blog"
      length: 20

extra_css:
  - stylesheets/extra.css